baseURL = 'https://kero.blog/'
languageCode = 'zh-CN'
title = '电脑星人'
theme = 'littlestyleplease'

[permalinks]
categories = "/categories/:slug/"

[markup.goldmark.renderer]
unsafe = true

[params.artalk]
server = 'https://service-cvddowek-1255707222.gz.apigw.tencentcs.com/'
site = '电脑星人的博客'

[params.umami]
websiteId = '41435ecc-7d57-4f52-9076-1479f3e17155'
hostUrl = 'https://service-ngoos1nm-1255707222.gz.apigw.tencentcs.com'
