baseURL = 'https://kero.blog/'
languageCode = 'zh-CN'
title = '电脑星人'
theme = 'littlestyleplease'

[permalinks]
categories = "/categories/:slug/"

[markup.goldmark.renderer]
unsafe = true

[params.artalk]
server = 'https://service-cvddowek-1255707222.gz.apigw.tencentcs.com/'
site = '电脑星人的博客'

[params.umami]
websiteId = '522309c7-a088-4510-b463-cc55efc48534'
hostUrl = 'https://accelerate.pageview.kero.blog'
