[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "max-age=2592000, immutable"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "max-age=2592000, immutable"

[[headers]]
  for = "/assets/lib/*"
  [headers.values]
    Cache-Control = "max-age=2592000, immutable"
